nameOverride: api-chart
replicaCount: 1
image:
  repository: sergios21/patrones_api
  pullPolicy: IfNotPresent
  tag: "v1.0"
service:
  type: ClusterIP
  port: 8080
resources:
  limits:
    cpu: "250m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "128Mi"
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []
  
